project:
  type: website
  resources: 
    - "CNAME"
    - "d38c7dd7d9bc1f5ecaec28c68956ff21.txt"

website:
  title: "谭长德网志"
  description: "渡己渡人 求真求善"
  site-url: https://tanchangde.com/
  favicon: favicon.png
  open-graph: true
  back-to-top-navigation: true
  reader-mode: true
  google-analytics: "G-1YFYY3SM29"
  navbar:
    left:
      - href: columns/investment.qmd
        text: "投研笔记"
      - href: columns/symbiotic-ai.qmd
        text: "共生智能"
      - href: columns/life.qmd
        text: "生活随笔"
      - href: columns/projection.qmd
        text: "高维投影"
      - href: about.qmd
        text: 关于
      - href: subscribe.html
        text: 订阅
      - icon: github
        href: https://github.com/tanchangde
      - icon: cc-circle
        href: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh-hans
      - icon: rss
        href: index.xml
  page-footer:
    center: |
      <p>
        <a href="https://beian.miit.gov.cn/" target="_blank" rel="noopener noreferrer">
          湘 ICP 备 2025126355 号</a>
      </p>
    background: light
format:
  html:
    theme: minty
    css: styles.css
    toc: true
    include-in-header:
      text: |
        <meta name="baidu-site-verification" content="codeva-E8RsxZLVdn" />
freeze: auto
execute:
  cache: true
lang: zh

preview:
  browser: true
  watch-inputs: true

