project:
  type: website

website:
  title: "谭长德网志"
  description: "渡己渡人 求真求善"
  site-url: https://tanchangde.com/
  favicon: favicon.png
  open-graph: true
  back-to-top-navigation: true
  reader-mode: true
  google-analytics: "G-1YFYY3SM29"
  navbar:
    left:
      - href: index.qmd
        text: 首页
      - href: about.qmd
        text: 关于
      - href: subscribe.html
        text: 订阅
      - icon: github
        href: https://github.com/tanchangde
      - icon: cc-circle
        href: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh-hans
      - icon: rss
        href: index.xml
  page-footer:
    center: |
      <p>
        <a href="https://beian.miit.gov.cn/" target="_blank" rel="noopener noreferrer">
          湘 ICP 备 2025126355 号</a>

        本站由<a href="https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral"><img src="/upyun_logo4.png"  height="30"></a>提供 CDN 加速/云存储服务
      </p>
    background: light
format:
  html:
    theme: lux
    css: styles.css
    toc: true
    include-in-header:
      text: |
        <meta name="baidu-site-verification" content="codeva-E8RsxZLVdn" />
freeze: auto
execute:
  cache: true
lang: zh

preview:
  browser: true
  watch-inputs: true

